server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spboot_tmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: 10.100.2.124
    port: 6379
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms

    timeout: 1000ms

  cache:
    cache-names: redisCache
    redis:
      cache-null-values: true
      key-prefix:
      time-to-live: 0ms
      use-key-prefix: true
    type: redis

#    tomcat:
#      max-idle: 10
#      max-active: 50
#      max-wait: 10000
#      initial-size: 5

logging:
 level:
    root: debug
    org:
      sprinngframework: debug
      org:
        mybatis: debug
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.spboot.db.pojo
  type-handlers-package: com.spboot.db.handler
