#server.port=8080
#spring.application.name=local-grpc-client
#grpc.client.local-grpc-server.host=127.0.0.1
#grpc.client.local-grpc-server.port=9898
#grpc.client.local-grpc-server.enableKeepAlive=true
#grpc.client.local-grpc-server.keepAliveWithoutCalls=true
grpc:
  client:
    local-ser:
      host: 127.0.0.1
      port: 9876
server:
  port: 8087
#spring:
#  application:
#    name: local-ser
